Vagrant.configure("2") do |config|
  villains = ["thanos", "jocker", "magneto"]
  (0..2).each do |i|
    config.vm.hostname = villains[i]
    config.vm.box = "ubuntu/bionic64"
    config.vm.box_check_update = false
    config.vm.network "public_network", bridge: "Realtek PCIe GbE Family Controller", ip: "192.168.1.120"
    config.vm.provision "shell", path: "entry_point.sh"
    config.vm.provider "virtualbox" do |vb|
      vb.name = villains[i]
      vb.memory = 2048
      vb.cpus = 2
    end
  end 
end
