Vagrant.configure("2") do |config|
  villains = ["thanos", "galactus", "loki"]
  villains.each_with_index do |villain, i|
      machine_name = i === 0 ? "master_node_#{villain}" : "worker_node_#{villain}"
      puts "Provisioning the machine: " + machine_name
      config.vm.define machine_name do |node|
          node.vm.hostname = villain
          node.vm.box = "ubuntu/bionic64"
          node.vm.box_check_update = false
          node.vm.network "public_network", bridge: "Realtek PCIe GbE Family Controller", ip: "192.168.1.12#{i}"
          node.vm.provision "shell", inline: "echo VM worker_node_#{villain} IS UP"
          node.vm.provider "virtualbox" do |vb|
              vb.name = villain
              vb.memory = 2048
              vb.cpus = 2
          end
      end
  end    
end
